name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.13.2
      with:
        version: 6.1.0
        arch: ${{ matrix.config.arch }}
        aqtversion: ==1.2.0 # optional, default is ==1.1.3

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DQV2RAY_PYBIND_STUBGEN=ON
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Generate stub
      run: |
        pip install mypy
        ${{github.workspace}}/build/embedded_python

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: qv2raybase-stubs.zip
        path: ${{github.workspace}}/out
